version: '2'
services:
  atlassian-jira-build:
    image: maven:3-jdk-8-alpine
    volumes:
      - ./atlassian-jira-software-7.2.1-source:/usr/src/mymaven
      - ./third-party-libraries:/usr/src/third-party-libraries
      - ./entrypoint.sh:/usr/src/mymaven/entrypoint.sh
    working_dir: /usr/src/mymaven
    command: ./entrypoint.sh